import { CodeSandbox as CodeSandboxSDK, Sandbox } from '@codesandbox/sdk';
import fs from 'fs';
import path from 'path';
import { Command, ICodeSandBox } from '../interfaces/CodeSandBox';

const TEMPLATE_ID = 'fxis37';

export class CodeSandBox implements ICodeSandBox<Sandbox> {
  private readonly sdk: CodeSandboxSDK;
  private sandbox: Sandbox | null = null;

  constructor() {
    this.sdk = new CodeSandboxSDK(process.env.CODESANDBOX_API_KEY);
  }

  async createSandbox(activeSandboxId?: string) {
    if (activeSandboxId) {
      this.sandbox = await this.sdk.sandbox.open(activeSandboxId);
    } else {
      this.sandbox = await this.sdk.sandbox.create({
        template: TEMPLATE_ID,
        title: 'Webcraft Generated App',
        description: 'An application generated by Webcraft AI',
        autoConnect: true,
        hibernationTimeoutSeconds: 60, // 1 minute
      });
    }

    return this.sandbox;
  }

  /**
   * Gets the preview URL for the sandbox
   * @returns Promise with the preview URL
   * @throws Error if sandbox is not initialized
   */
  async getPreviewUrl(): Promise<string> {
    this.ensureSandboxInitialized();
    const port = await this.sandbox.ports.waitForPort(3000);
    return port.getPreviewUrl();
  }

  async copyFile(filePath: string, newFilePath: string) {
    this.ensureSandboxInitialized();
    await this.sandbox.fs.copy(filePath, newFilePath);
  }

  /**
   * Writes binary content to a file
   * @param filePath Path to the file
   * @param content Binary content as Uint8Array
   */
  async writeFile(filePath: string, content: Uint8Array) {
    this.ensureSandboxInitialized();
    await this.sandbox.fs.writeFile(filePath, content);
  }

  /**
   * Reads binary content from a file
   * @param filePath Path to the file
   * @returns Binary content as Uint8Array
   */
  async readFile(filePath: string): Promise<Uint8Array> {
    this.ensureSandboxInitialized();
    return this.sandbox.fs.readFile(filePath);
  }

  /**
   * Lists files and directories at the specified path
   * @param dirPath Path to the directory
   * @returns Array of directory entries
   */
  async listDirectory(dirPath: string) {
    this.ensureSandboxInitialized();
    return this.sandbox.fs.readdir(dirPath);
  }

  /**
   * Deletes a file or directory
   * @param filePath Path to the file or directory
   */
  async deleteFile(filePath: string, recursive?: boolean) {
    this.ensureSandboxInitialized();
    await this.sandbox.fs.remove(filePath, recursive);
  }

  /**
   * Renames a file or directory
   * @param oldPath Current path
   * @param newPath New path
   */
  async rename(oldPath: string, newPath: string) {
    this.ensureSandboxInitialized();
    await this.sandbox.fs.rename(oldPath, newPath);
  }

  /**
   * Downloads a file from the sandbox to the local filesystem
   * @param remotePath Path in the sandbox
   * @param localPath Local path to save the file
   */
  async downloadFile(remotePath: string, localPath: string) {
    this.ensureSandboxInitialized();
    const { downloadUrl } = await this.sandbox.fs.download(remotePath);
    const response = await fetch(downloadUrl);

    if (!response.ok) {
      throw new Error(`Failed to download file: ${response.statusText}`);
    }

    const file = await response.blob();
    const arrayBuffer = await file.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);

    // Ensure the directory exists
    const dir = path.dirname(localPath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    fs.writeFileSync(localPath, buffer);
  }

  /**
   * Writes text content to a file
   * If file doesn't exist, it will be created
   * If file exists, it will be overwritten
   * @param filePath Path to the file
   * @param content Text content
   */
  async writeTextFile(filePath: string, content: string) {
    this.ensureSandboxInitialized();
    await this.sandbox.fs.writeTextFile(filePath, content);
  }

  /**
   * Reads text content from a file
   * @param filePath Path to the file
   * @returns Text content
   */
  async readTextFile(filePath: string): Promise<string> {
    this.ensureSandboxInitialized();
    return this.sandbox.fs.readTextFile(filePath);
  }

  async runCommand(command: Command): Promise<{
    output: string;
    exitCode?: number;
  }> {
    this.ensureSandboxInitialized();
    const shell = await this.sandbox.shells.run(command);

    return shell;
  }

  /**
   * Creates a directory if it doesn't exist
   * @param dirPath Path to create
   */
  async createDirectory(dirPath: string, recursive = true) {
    this.ensureSandboxInitialized();
    await this.sandbox.fs.mkdir(dirPath, recursive);
  }

  async setupGit(remote: string) {
    this.ensureSandboxInitialized();
    console.log(remote);
    await this.gitInit();
    await this.sandbox.shells.run(
      'git config --global user.email "webcraft@dev.webcraft.ai"',
    );
    await this.sandbox.shells.run(
      'git config --global user.name "Webcraft AI"',
    );
    await this.gitAdd();
    await this.gitCommit('Initial commit');
    await this.setGitRemote(remote);
    await this.gitPush();
  }

  async gitInit() {
    this.ensureSandboxInitialized();
    // await this.deleteFile('/project/workspace/.git', true);
    const shell = await this.sandbox.shells.run('git init');
    console.log('git init', shell);
    return shell;
  }

  async gitAdd() {
    this.ensureSandboxInitialized();
    const shell = await this.sandbox.shells.run('git add .');
    console.log('git add', shell);
    return shell;
  }

  async gitCommitAndPush(message: string) {
    this.ensureSandboxInitialized();
    await this.gitCommit(message);
    await this.gitPush();
  }

  async gitCommit(message: string) {
    this.ensureSandboxInitialized();
    await this.gitAdd();
    const shell = await this.sandbox.shells.run(`git commit -m "${message}"`);
    console.log('git commit', shell);
    return shell;
  }

  async gitPush() {
    this.ensureSandboxInitialized();
    console.log('will git push');

    // Create a new shell
    const shell = await this.sandbox.shells.create('bash');

    shell.write('git push --set-upstream origin main');

    console.log('wrote command');

    // Listen to shell output
    shell.onOutput((output) => {
      console.log('output', output);
      if (output.includes('git push')) {
        shell.write('\n');
        // Handle authentication if needed
        // shell.write(process.env.GITHUB_USERNAME || 'webcraft');
      }
      if (output.includes('Username for')) {
        console.log('writing username');
        shell.write(process.env.GITHUB_USERNAME || 'webcraft');
        shell.write('\n');
      }
      // Press Enter
    });

    console.log('here');

    // // Kill the shell when done
    // await shell.kill();

    // // Dispose the listener when done
    // shellListenDisposer.dispose();
  }

  async setGitRemote(remote: string) {
    this.ensureSandboxInitialized();
    const shell = await this.sandbox.shells.run(
      `git remote set-url origin ${remote}`,
    );
    console.log('git remote set-url origin', shell);
    return shell;
  }

  /**
   * Ensures the sandbox is initialized before performing operations
   * @throws Error if sandbox is not initialized
   */
  private ensureSandboxInitialized() {
    if (!this.sandbox) {
      throw new Error('Sandbox not initialized. Call createSandbox() first.');
    }
  }
}
